env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
settings:
  react:
    version: 'detect'
rules:
  'prettier/prettier': [error, { 'endOfLine': 'auto' }]
  'react/react-in-jsx-scope': off
  'react/jsx-filename-extension': [error, { 'extensions': ['.tsx', '.ts'] }]
  '@typescript-eslint/no-unused-vars': off
  # '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-extra-semi': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-explicit-any': error
  'react/prop-types': off
  '@typescript-eslint/restrict-plus-operands': off
  '@typescript-eslint/no-unsafe-assignment': off
